---

## Connect to a master instance or Redis
redis:

  port: 6379
  host: "127.0.0.1"
  db: 3
#  password: ""

## Or alternatively, connect to Redis Sentinel
# redis:
#   name: "mymaster"
#   password: ""
#   db: 3
#   sentinels:
#     - host: "1.2.3.4"
#       port: 26379
#     - host: "1.2.3.5"
#       port: 26379
#     - host: "1.2.3.6"
#       port: 26379

mongo:

  # connection string for main messages database
  url: "mongodb://127.0.0.1:27017/wildduck"

  ## database name or connection string for the users db
  #users: "users"

  ## database name or connection string for the attachments db
  #gridfs: "attachments"

  ## database name or connection string for the outbound queue
  sender: "zone-mta"

sender:
  # Push messages to ZoneMTA queue for delivery
  # if `false` then no messages are sent
  enabled: true

  # which ZoneMTA queue to use by default. This mostly affects forwarded messages
  zone: "default"

  # Collection name for GridFS storage
  gfs: "mail"

  # Collection name for the queue
  # see [dbs].sender option for choosing correct database to use for ZoneMTA queues
  # by default the main wildduck database is used
  collection: "zone-queue"

srs:
  # must be shared with ZoneMTA SRS config, otherwise messages sent from ZoneMTA are not recognized by Haraka
  secret: "secret value"

attachments:
  type: "gridstore"
  bucket: "attachments"
  decodeBase64: true

log:
  authlogExpireDays: 30

limits:
  windowSize: 3600 # 1 hour
  rcpt: 150 # allowed messages for the same recipient during window size

spamHeaders:
  # If this header exists and starts with "yes" then the message is treated as spam
  # This is SpamAssassin header.
  - key: "X-Spam-Status"
    value: "^yes"
    target: "\\Junk"

  # If this header exists and starts with "yes" then the message is treated as spam
  # This is Rspamd header. For the same with SpamAssassin use "X-Spam-Status"
  - key: "X-Rspamd-Spam"
    value: "^yes"
    target: "\\Junk"

  # Treat as spam if message has header with 6 or more plus signs:
  #   X-Rspamd-Bar: ++++++
  - key: "X-Rspamd-Bar"
    value: "^\\+{6}"
    target: "\\Junk"

  # If this header has a value, then it contains a virus, treat as spam
  - key: "X-Haraka-Virus"
    value: "."
    target: "\\Junk"
